name: Step 1

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  check_keywords:
    name: Check exercise comment text
    runs-on: ubuntu-latest
    steps:
      - name: Check for required references
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENT_BODY" | grep -qi professortocat
          echo "$COMMENT_BODY" | grep -qi coverage
