name: Step 3

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_test_case:
    name: Check test case
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Confirm Fibonacci test is enabled
        run: '! grep -q "# def test_get_nth_fibonacci_ten" tests/calculations_test.py'
